"""add tele consultation

Revision ID: a55fa5080766
Revises: 55ad9739d077
Create Date: 2026-04-26 19:43:33.887255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55fa5080766'
down_revision: Union[str, Sequence[str], None] = '55ad9739d077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tele_consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('chw_id', sa.Integer(), nullable=False),
    sa.Column('oncologist_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('response', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'REVIEWED', name='consultation_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['chw_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['oncologist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query'),
    sa.UniqueConstraint('response')
    )
    op.create_index(op.f('ix_tele_consultations_id'), 'tele_consultations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tele_consultations_id'), table_name='tele_consultations')
    op.drop_table('tele_consultations')
    # ### end Alembic commands ###
